#SPDX-License-Identifier: MIT-0
---
# defaults file for install_barman
master_ip: '192.168.20.231' 
master_user: 'postgres'
barman_ip: '192.168.20.233' 
barman_user: 'barman' 
barman_user_password: 'Otus2022!'
postgres_ver: 18